Feat/main page stylings
gzaripov/aviasales-frontend pull request #2
Opened 2018-02-20 07:42 UTC by gzaripov

Improve appearance of main page.

2018-02-22 19:39 UTC, imevro requested changes

2018-02-22 19:39 UTC, evgenyrodionov commented on src/Destinations/Category.js
> +    transform: ${props => (CategoryButton.active ? "" : "translateY(-5px);")};
что за нахуй с CategoryButton.active?

2018-02-22 19:39 UTC, evgenyrodionov commented on src/Prices/CityCard/index.js
> +const Prices = styled(props => (
в нормальный компонент вынеси, чё это за дичь?

2018-02-23 13:59 UTC, gzaripov commented
https://build-uljurxgzxy.now.sh/

2018-02-25 11:58 UTC, imevro approved these changes

2018-02-25 11:58 UTC, evgenyrodionov commented
Смерджу после #3

2018-09-16 16:07 UTC, merged