Feat/search page
gzaripov/aviasales-frontend pull request #4
Opened 2018-02-22 00:33 UTC by gzaripov

Сверстана мобильная версия страницы результатов поиска.
https://build-uljurxgzxy.now.sh/

2018-02-22 19:36 UTC, evgenyrodionov commented
Как с главной страницы перейти?

2018-02-22 19:36 UTC, evgenyrodionov commented
Кривая верстка какая-то

![image](https://user-images.githubusercontent.com/775692/36560105-e1201ab2-1820-11e8-8b01-cc9b61cb6ed9.png)

2018-02-22 19:40 UTC, evgenyrodionov commented
Мерджконфликты у тебя, исправляй

2018-02-22 19:42 UTC, evgenyrodionov commented
Ок, я вернул обратно на мастер, т.к. ты от него делал бранч, но не очень понял этого: а как ты собираешься потом мерджить две различные ветки?

2018-02-22 19:59 UTC, imevro requested changes

2018-02-22 19:59 UTC, evgenyrodionov commented on src/Search/Header/SearchForm/Dates/index.js
> +const DividerDiv = styled.div`
hr

2018-02-22 19:59 UTC, evgenyrodionov commented on src/Search/Header/SearchForm/index.js
> +  margin: -2px;
фу, нахуй отрицательные марджины

2018-02-22 19:59 UTC, evgenyrodionov commented on src/Search/Header/SearchForm/index.js
> +const RoundBox = styled.div`
RectangleOval

2018-02-22 19:59 UTC, evgenyrodionov commented on src/Search/Tickets/Ticket.js
> +const Logos = styled(props => (
опять эта дичь

2018-02-22 19:59 UTC, evgenyrodionov commented on src/Search/Tickets/Ticket.js
> +  console.log("null");
фу

2018-02-22 19:59 UTC, evgenyrodionov commented on src/Search/Tickets/Ticket.js
> +  if (props.status === "cheapest") {
читай второй урок первого этапа, раздел про switch case и проч

2018-02-22 19:59 UTC, evgenyrodionov commented on src/Search/Tickets/Ticket.js
> +const FlightTime = styled.p`
htmlreference.io/element/time

2018-02-22 19:59 UTC, evgenyrodionov commented on src/Search/Tickets/Ticket.js
> +          <div className="col-xs-4">
а зачем тут сетка?

2018-02-22 19:59 UTC, evgenyrodionov commented on src/Search/Tickets/Ticket.js
> +    <MobileContent data={props.data} />
зачем ты завёл прокладку?

2018-02-22 19:59 UTC, evgenyrodionov commented on src/Search/Tickets/index.js
> +const ticketsData = [
ты и так в директории тикетс, зачем тебе этот префикс

2018-02-24 09:57 UTC, gzaripov commented
https://build-wbakshmpoj.now.sh/search

2018-02-28 08:52 UTC, gzaripov commented
https://build-aiygqkfdno.now.sh/search

2018-03-01 20:45 UTC, evgenyrodionov commented
С главной страницы при клике на кнопку не переходит

2018-03-01 20:46 UTC, evgenyrodionov commented
Логотип мыльный
![image](https://user-images.githubusercontent.com/775692/36868857-b6bc9a04-1daa-11e8-94bd-48e3c9866c20.png)

2018-03-01 20:46 UTC, evgenyrodionov commented
Крест уехал
![image](https://user-images.githubusercontent.com/775692/36868889-cb22539e-1daa-11e8-82c6-05cbc7a652bb.png)

2018-03-01 20:54 UTC, imevro requested changes
очень сложно и тяжко

2018-03-01 20:54 UTC, evgenyrodionov commented on src/App.js
> +import ru from "react-intl/locale-data/fr";
?

2018-03-01 20:54 UTC, evgenyrodionov commented on src/Main/Header/SearchForm/index.js
> +import Dates from "../../../common/Dates";
зачем эта директория common? ты свалку устраиваешь там?

2018-03-01 20:54 UTC, evgenyrodionov commented on src/Main/Prices/CityCard/index.js
> +  border-bottom: ${p => (p.types.last ? "none" : "0.5px dashed #afbec6")};
не очень понимаю что значит этот проп

2018-03-01 20:54 UTC, evgenyrodionov commented on src/Main/Prices/CityCard/index.js
> +    padding-left: ${props => (props.types.threeMultiple ? "0" : "18px")};
чё за жесть?

2018-03-01 20:54 UTC, evgenyrodionov commented on src/Main/Prices/CityCard/index.js
> +    padding-left: ${props => (props.types.threeMultiple ? "0" : "18px")};
на трёх строчках

2018-03-01 20:54 UTC, evgenyrodionov commented on src/Main/Prices/CityCard/index.js
> +    padding-left: ${props => (props.types.threeMultiple ? "0" : "18px")};
как это понимать другому человеку?

2018-03-01 20:54 UTC, evgenyrodionov commented on src/Main/Prices/index.js
> +const getCardTypes = (id, length) => {
соблюдай консистентность: если передаешь индекс, то и работай тут с индексом, а не с неведомым idx

а вообще конечно сама функция чушь ненужная

2018-03-01 20:54 UTC, evgenyrodionov commented on src/Search/Filters/Airlines.js
> +    price: ""
откуда тут строка взялась это раз
почему она пустая если есть нулл и андефайнед это два

2018-03-01 20:54 UTC, evgenyrodionov commented on src/Search/Filters/Checkbox.js
> +    text: this.props.text
либо пропы, либо стейт. не нужно их смешивать — заебешься с синхронизацией данных

2018-03-01 20:54 UTC, evgenyrodionov commented on src/Search/Filters/Checkbox.js
> +    text: this.props.text
источник данных должен быть един

2018-03-01 20:54 UTC, evgenyrodionov commented on src/Search/Filters/TravelTime.js
> +          <From>от 04ч 20м</From>
04?

2018-03-01 20:54 UTC, evgenyrodionov commented on src/Search/Tickets/MobileTicket/index.js
> +  return null;
`return flightStatuses[props.status] || null`

2018-03-01 20:54 UTC, evgenyrodionov commented on src/Search/Tickets/TabletTicket/index.js
> +        {suitcase !== false &&
на тернарник переделай

2018-03-01 20:54 UTC, evgenyrodionov commented on src/Search/Tickets/TabletTicket/index.js
> +        {typeof suitcase === "number" && (
тебе не кажется что это неправильно когда у одного пропа могут быть разные типы

2018-03-01 20:54 UTC, evgenyrodionov commented on src/Search/Tickets/TabletTicket/index.js
> +            {generateBaggage(props.data.baggage.alternative)}
почему generate

2018-03-01 20:54 UTC, evgenyrodionov commented on src/Search/index.js
> +class ScrollToTop extends Component {
а зачем ты своё компонент сделал, нет готовых?

2018-03-01 20:54 UTC, evgenyrodionov commented on src/common/DatePickerInput/Cell.js
> +  margin-left: ${p => (p.isEnd ? "5px" : "")};
зачем такие пропы передавать?

2018-03-01 20:54 UTC, evgenyrodionov commented on src/common/DatePickerInput/index.js
> +  if (!date) return "";
опять пустая строка

2018-03-01 20:54 UTC, evgenyrodionov commented on src/common/DatePickerInput/index.js
> +      period.from = date;
фу мутабельность

2018-03-01 20:54 UTC, evgenyrodionov commented on src/common/DatePickerInput/styled.js
> +   .DayPicker-Day--end:after {
зачем это тут? в цсс положи

2018-03-03 08:54 UTC, gzaripov commented
https://build-tunidsmqvm.now.sh/search

2018-03-04 17:54 UTC, imevro requested changes

2018-03-04 17:54 UTC, evgenyrodionov commented on src/Search/Tickets/TabletTicket/Flight.js
> +  dateParts[3] = dateParts[3].charAt(0).toUpperCase() + dateParts[3].slice(1);
1) что это за мутабельность
2) что это за ебучий треш

2018-03-04 17:54 UTC, evgenyrodionov commented on src/Search/Tickets/TabletTicket/Flight.js
> +  dateParts[3] = dateParts[3].charAt(0).toUpperCase() + dateParts[3].slice(1);
как это вообще читать? что тут происходит?

2018-03-04 17:54 UTC, evgenyrodionov commented on src/Search/Tickets/TabletTicket/index.js
> +        {suitcase === -1 ? (
как может быть -1?

2018-03-04 17:54 UTC, evgenyrodionov commented on src/Search/Tickets/TabletTicket/index.js
> +        {suitcase === -1 ? (
ты конечно тот ещё любитель костылей

2018-03-04 17:54 UTC, evgenyrodionov commented on src/Search/Tickets/index.js
> +const MINUTES_IN_HOUR = 60;
типа люди не догадаются?

2018-03-04 20:38 UTC, gzaripov commented
Поправил свой говнокод.
https://build-rdehqevbjo.now.sh/search

2018-03-07 17:18 UTC, imevro requested changes

2018-03-07 17:18 UTC, evgenyrodionov commented on src/Search/Tickets/TabletTicket/Flight.js
> +import capitalizeFirstLetter from "ucfirst";
похвально, но есть лоудеш и `_.capitalize`

2018-03-07 17:18 UTC, evgenyrodionov commented on src/Search/Tickets/TabletTicket/Flight.js
> +  // take first 3 symbols ex. фев. => фев, март => мар
а нахуя ты этим занимаешься если в дейт-фнс есть format?

2018-03-08 09:19 UTC, gzaripov commented
https://build-ipvsculmgj.now.sh/

2018-03-09 10:04 UTC, imevro approved these changes

2018-09-16 13:33 UTC, merged