Refactor/airbnb code style
gzaripov/aviasales-frontend pull request #5
Opened 2018-03-07 08:45 UTC by gzaripov

Добавил кодстайл от airbnb.
https://build-guadkurebo.now.sh/

2018-03-07 21:25 UTC, imevro requested changes

2018-03-07 21:25 UTC, evgenyrodionov commented on .eslintrc
> +    "jsx-quotes": ["error", "prefer-single"]
1) https://github.com/KonstBessonov/aviasales-demo-frontend/pull/5#pullrequestreview-102100231

2) зачем ты трогаешь правила без согласования?

2018-03-07 21:25 UTC, evgenyrodionov commented on package.json
> +    "babel-eslint": "^8.2.2",
почему не в дев

2018-03-08 10:27 UTC, gzaripov commented
https://build-wpmlwbjmkf.now.sh/

2018-03-09 10:05 UTC, imevro requested changes

2018-03-09 10:05 UTC, evgenyrodionov commented on package.json
> +    "eslint-config-airbnb": "16.1.0"
а остальные, которые указаны в пирдепс? перечитай установку

2018-03-10 12:12 UTC, imevro approved these changes

2018-09-16 13:33 UTC, merged