Feat/search page filters
gzaripov/aviasales-frontend pull request #6
Opened 2018-03-10 08:59 UTC by gzaripov

Реализовал фильтры.
https://build-akzaseujth.now.sh/

2018-03-10 14:23 UTC, imevro commented
Креста сброса у фильтров нет

Если не работает, то и не отображай
![image](https://user-images.githubusercontent.com/775692/37243262-a16ae8e8-2487-11e8-95c7-0fabd0746928.png)

2018-03-10 14:32 UTC, imevro requested changes
очень даже неплохо, хоть и комментариев много. красивая архитектура работы с фильтрами

2018-03-10 14:32 UTC, evgenyrodionov commented on package.json
> +    "lodash.set": "^4.3.2",
зачем?

2018-03-10 14:32 UTC, evgenyrodionov commented on src/Header/Dates/index.js
> +import DatePickerInput from '../DatePickerInput/index';
зачем тут указан индекс?

2018-03-10 14:32 UTC, evgenyrodionov commented on src/Header/PassengerAndClass.js
> +import arrowDown from '../Search/Header/SearchForm/icons/arrow_down.svg';
тебе не кажется что это очень странно в такие недра погружаться ради одной иконки?

2018-03-10 14:32 UTC, evgenyrodionov commented on src/Header/PassengerAndClass.js
> +const Class = styled.span`
лучше не использовать такой нейминг, потому что могут быть коллизии с резервным словом `class`

2018-03-10 14:32 UTC, evgenyrodionov commented on src/Header/PassengerAndClass.js
> +  return sum(Object.values(passengers));
есть же .length у массива

2018-03-10 14:32 UTC, evgenyrodionov commented on src/Header/PassengerAndClass.js
> +    this.setState({ ...this.state, passengerCount, isBusinessClass });
не нужно засовывать старый стейт, потому что `setState` обновляет только указанные ключи

2018-03-10 14:32 UTC, evgenyrodionov commented on src/Header/PassengerAndClassPicker.js
> +// onChange={onChangeCheckbox}
мусор вынеси

2018-03-10 14:32 UTC, evgenyrodionov commented on src/Search/Filters/Airlines.js
> +    this.props.onChange(`airlines.${path}`, value);
ну хуй знает насчёт такого пути

2018-03-10 14:32 UTC, evgenyrodionov commented on src/Search/Filters/Airlines.js
> +    this.props.onChange(`airlines.${path}`, value);
в целом сносно, но если есть чё получше — можем обсудить в чате

2018-03-10 14:32 UTC, evgenyrodionov commented on src/Search/Filters/CheckGroup.js
> +  checklist.splice(index, 1, { ...checklist[index], checked });
опять мутабельность

2018-03-10 14:32 UTC, evgenyrodionov commented on src/Search/Filters/CheckGroup.js
> +  checklist.splice(index, 1, { ...checklist[index], checked });
да и вся функция сложная

2018-03-10 14:32 UTC, evgenyrodionov commented on src/Search/Filters/CheckGroup.js
> +function checkAllChecks(checklist, checked) {
чек чек чек чек

2018-03-10 14:32 UTC, evgenyrodionov commented on src/Search/Filters/CheckGroup.js
> +function checkAllChecks(checklist, checked) {
заебывает

2018-03-10 14:32 UTC, evgenyrodionov commented on src/Search/Filters/CheckGroup.js
> +    onChange(checkAllChecks(checklist, allChecksChecked));
ставь переносы

2018-03-10 14:32 UTC, evgenyrodionov commented on src/Search/Filters/Filter/index.js
> +        <Panel header={Header({ opened, title, amount })} showArrow={false} key="1">
а почему ты реакт-компонент вызываешь как функцию

2018-03-10 14:32 UTC, evgenyrodionov commented on src/Search/Filters/index.js
> +        <Airports {...airports} onChange={this.onDataChange} />
явное лучше неявного, поэтому вместо спред-оператора в пропах распиши каждый проп либо утилизуй всё под каким-нибудь `data`

2018-03-10 14:32 UTC, evgenyrodionov commented on src/common/ui/Counter/index.js
> +        <Increment disabled={disabled || value >= max} onClick={this.handleClick(1)} type="button">
почему не +1?

2018-03-10 17:00 UTC, gzaripov commented
https://build-cwlxarsyfv.now.sh/

2018-03-12 08:58 UTC, gzaripov commented
https://build-zwazyuermc.now.sh/search

2018-03-13 06:41 UTC, imevro requested changes
и сделай чтобы при клике на инпут выбора аэропорта открывался дропдаун, а то сейчас не и это не очень очевидно

2018-03-13 06:41 UTC, evgenyrodionov commented on .vscode/launch.json
> +  "configurations": [
что это тут делает

2018-03-13 06:41 UTC, evgenyrodionov commented on src/Main/Header/SearchForm/index.js
> +      iata: '',
а зачем хранить аж три поля, если достаточно код iata, а по нему уже определять город и страну?

2018-03-14 08:59 UTC, gzaripov commented
https://build-dnjzxqtkwl.now.sh/

2018-09-16 13:31 UTC, merged